Repository Macaulay2/M2, pull requests merged in 2020-05, with the labels that each got.

#1072 simplify (show, URL)
  M2/Macaulay2/m2/html.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc1.m2
Labels: under discussion

#1141 Fix bug in some MutableMatrix methods
  M2/Macaulay2/m2/mutablemat.m2
  M2/Macaulay2/packages/Chordal.m2
  M2/Macaulay2/tests/normal/mutmat.m2
Labels: waiting for update

#1192 Updated the FastLinAlg package
  M2/Macaulay2/packages/FastLinAlg.m2
Labels: waiting for review

#1065 Dockerfiles for M2
  M2/BUILD/docker/.gitignore
  M2/BUILD/docker/Dockerfile
  M2/BUILD/docker/Makefile
  M2/BUILD/docker/README.md
  M2/BUILD/docker/emacs-docker.el
Labels: waiting for update

#1047 FGLM v1.1.0: moved core algorithms to the engine
  M2/Macaulay2/d/interface.dd
  M2/Macaulay2/e/engine.h
  M2/Macaulay2/e/lapack.hpp
  M2/Macaulay2/e/mat-linalg.hpp
  M2/Macaulay2/e/mat.hpp
  M2/Macaulay2/e/mutablemat-defs.hpp
  M2/Macaulay2/e/mutablemat-imp.hpp
  M2/Macaulay2/e/x-mutablemat.cpp
  M2/Macaulay2/packages/FGLM.m2
Labels: waiting for review

#1196 minor expression update; major WebApp mode update
  M2/Macaulay2/d/startup.m2.in
  M2/Macaulay2/m2/expressions.m2
  M2/Macaulay2/m2/modules.m2
  M2/Macaulay2/m2/quotring.m2
  M2/Macaulay2/m2/undoc.m2
  M2/Macaulay2/m2/varieties.m2
  M2/Macaulay2/m2/webapp.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/htmlWithTex-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/texMath-doc.m2
Labels: under discussion
