Repository Macaulay2/M2, pull requests merged in 2020-11, with the labels that each got.

#1593 Update Cremona.m2
  M2/Macaulay2/packages/CoincidentRootLoci/tests.m2
  M2/Macaulay2/packages/Cremona.m2
  M2/Macaulay2/packages/Cremona/documentation.m2
  M2/Macaulay2/packages/SpecialFanoFourfolds.m2
Labels: waiting for update

#1387 Fixing internal tests, part 1
  .github/workflows/test_build.yml
  M2/Macaulay2/d/equality.dd
  M2/Macaulay2/tests/engine/raw-ring.m2
Labels: contributions welcome, waiting for review

#1587 Graphs 0.3.3, GraphicalModels 2.0, StatGraphs 0.1
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/GraphicalModels.m2
  M2/Macaulay2/packages/GraphicalModelsMLE.m2
  M2/Macaulay2/packages/Graphs.m2
  M2/Macaulay2/packages/StatGraphs.m2
Labels: waiting for review by package author(s)

#1611 in Posets.m2, implement the Coxeter Polynomial
  M2/Macaulay2/packages/Posets.m2
Labels: waiting for review by package author(s)

#1623 Add Hadamard initial release
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/Hadamard.m2
Labels: waiting for review

#1628 Change uses of \bf in math mode
  M2/Macaulay2/packages/BGG.m2
  M2/Macaulay2/packages/BeginningMacaulay2/tutorial
  M2/Macaulay2/packages/Macaulay2Doc/tu_Fano.m2
  M2/Macaulay2/packages/Macaulay2Doc/tu_canEmbed.m2
  M2/Macaulay2/packages/Macaulay2Doc/tu_divisors.m2
  M2/Macaulay2/packages/Macaulay2Doc/tu_elementary.m2
  M2/Macaulay2/packages/Quasidegrees.m2
  M2/Macaulay2/packages/ReflexivePolytopesDB.m2
  M2/Macaulay2/packages/SLnEquivariantMatrices.m2
Labels: waiting for review

#1618 Separation by zero-length regular expressions
  M2/Macaulay2/d/boost-regex.cpp
  M2/Macaulay2/tests/normal/regex.m2
Labels: waiting for review

#1612 Update poset-example.html
  M2/Macaulay2/packages/Visualize/digraph-example.html
  M2/Macaulay2/packages/Visualize/graph-example.html
  M2/Macaulay2/packages/Visualize/ideal2d-example.html
  M2/Macaulay2/packages/Visualize/ideal3d-example.html
  M2/Macaulay2/packages/Visualize/poset-example.html
  M2/Macaulay2/packages/Visualize/simplicial-complex-example.html
Labels: waiting for review by package author(s)

#1620 Package NoetherianOperators v1.0
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/NoetherianOperators.m2
Labels: waiting for update

#1373 StatePolytope updates
  M2/Macaulay2/packages/StatePolytope.m2
  M2/Macaulay2/packages/StatePolytope/examples/_initial__Ideals.out
  M2/Macaulay2/packages/StatePolytope/examples/_is__Stable.out
  M2/Macaulay2/packages/StatePolytope/examples/_polymake__State__Polytope_lp__Ideal_rp.out
  M2/Macaulay2/packages/StatePolytope/examples/_polymake__State__Polytope_lp__Z__Z_cm__Ideal_rp.out
  M2/Macaulay2/packages/StatePolytope/examples/_state__Polytope_lp__Ideal_rp.out
  M2/Macaulay2/packages/StatePolytope/examples/_state__Polytope_lp__Z__Z_cm__Ideal_rp.out
Labels: waiting for review by package author(s)
