Repository Macaulay2/M2, pull requests merged in 2020-12, with the labels that each got.

#1616 Update VirtualResolutions package to v1.3
  M2/Macaulay2/packages/Saturation.m2
  M2/Macaulay2/packages/VirtualResolutions.m2
  M2/Macaulay2/packages/VirtualResolutions/doc.m2
  M2/Macaulay2/packages/VirtualResolutions/tests.m2
Labels: waiting for test builds

#1546 Fix capture + several minor bug fixes
  M2/Macaulay2/d/actors5.d
  M2/Macaulay2/d/actors6.dd
  M2/Macaulay2/d/interp.dd
  M2/Macaulay2/m2/examples.m2
  M2/Macaulay2/m2/exports.m2
  M2/Macaulay2/m2/help.m2
  M2/Macaulay2/m2/indeterminates.m2
  M2/Macaulay2/m2/installPackage.m2
  M2/Macaulay2/m2/localring.m2
  M2/Macaulay2/m2/packages.m2
  M2/Macaulay2/m2/run.m2
  M2/Macaulay2/packages/CMakeLists.txt
  M2/Macaulay2/packages/Complexes.m2
  M2/Macaulay2/packages/Cremona.m2
  M2/Macaulay2/packages/DiffAlg.m2
  M2/Macaulay2/packages/GKMVarieties.m2
  M2/Macaulay2/packages/InvariantRing.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc1.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/Grassmannian-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/degreesRing-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/overviewC.m2
  M2/Macaulay2/packages/Macaulay2Doc/tu_Fano.m2
  M2/Macaulay2/packages/SimpleDoc.m2
Labels: Documentation, waiting for review

#1657 fixing isRanked in Posets
  M2/Macaulay2/packages/Posets.m2
Labels: waiting for review by package author(s)

#1661 Relax requirements for documentation nodes
  M2/Macaulay2/m2/code.m2
  M2/Macaulay2/m2/document.m2
  M2/Macaulay2/m2/examples.m2
  M2/Macaulay2/m2/exports.m2
  M2/Macaulay2/m2/format.m2
  M2/Macaulay2/m2/help.m2
  M2/Macaulay2/m2/html.m2
  M2/Macaulay2/m2/installPackage.m2
  M2/Macaulay2/m2/installedpackages
  M2/Macaulay2/m2/local.m2
  M2/Macaulay2/m2/methods.m2
  M2/Macaulay2/m2/packages.m2
  M2/Macaulay2/m2/shared.m2
  M2/Macaulay2/m2/undoc.m2
  M2/Macaulay2/m2/validate.m2
  M2/Macaulay2/m2/varieties.m2
  M2/Macaulay2/packages/Macaulay2Doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc1.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/cohomology-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/package-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/trim-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/shared.m2
  M2/Macaulay2/packages/MinimalPrimes.m2
  M2/Macaulay2/packages/MinimalPrimes/doc.m2
  M2/Macaulay2/packages/ModuleDeformations.m2
  M2/Macaulay2/packages/PHCpack/examples/_is__Witness__Set__Member_lp..._cm__Verbose_eq_gt..._rp.out
  M2/Macaulay2/packages/Saturation/saturate-test.m2
  M2/Macaulay2/packages/SimpleDoc.m2
  M2/Macaulay2/packages/SimplicialPosets.m2
  M2/Macaulay2/packages/Text.m2
  M2/Macaulay2/packages/VersalDeformations.m2
  M2/Macaulay2/tests/ComputationsBook/exterior-algebra/test.m2
  M2/Macaulay2/tests/ComputationsBook/exterior-algebra/test.out.expected
Labels: Documentation

#1511 adding the new package ResolutionsOfStanleyReisnerRings
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/Macaulay2Doc/overview_packages.m2
  M2/Macaulay2/packages/Makefile.in
  M2/Macaulay2/packages/ResolutionsOfStanleyReisnerRings.m2
  M2/configure.ac
Labels: waiting for update

#1675 GraphicalModelsMLE.m2 fixed bugs in solverMLE
  M2/Macaulay2/packages/GraphicalModelsMLE.m2
  M2/Macaulay2/packages/Posets.m2
Labels: waiting for test builds

#1694 Fixed Macaulay2/book
  M2/Macaulay2/CMakeLists.txt
  M2/Macaulay2/book/CMakeLists.txt
  M2/Macaulay2/book/Makefile.in
  M2/Macaulay2/book/book.m2
  M2/Macaulay2/book/booktex.m2
  M2/Macaulay2/m2/Makefile.in
  M2/Macaulay2/m2/book.m2
  M2/Macaulay2/m2/exports.m2
  M2/Macaulay2/m2/format.m2
  M2/Macaulay2/m2/help.m2
  M2/Macaulay2/m2/html.m2
  M2/Macaulay2/m2/installPackage.m2
  M2/Macaulay2/m2/latex.m2
  M2/Macaulay2/m2/loadsequence
  M2/Macaulay2/m2/markdown.m2
  M2/Macaulay2/m2/mathml.m2
  M2/Macaulay2/m2/methods.m2
  M2/Macaulay2/packages/CMakeLists.txt
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc14.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/comodule-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/matrix-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/nextPrime-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/package-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/solve-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/tex-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/texMath-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/groebner.m2
  M2/Macaulay2/packages/Macaulay2Doc/monomorderings.m2
  M2/Macaulay2/packages/Macaulay2Doc/overviewC.m2
  M2/Macaulay2/packages/Macaulay2Doc/tu_modules.m2
  M2/Macaulay2/packages/Style/M2book.tex.in
  M2/Macaulay2/packages/Style/papers.bib
  M2/cmake/latex.cmake
  M2/config/files
Labels: Documentation

#1696 Development
  M2/Macaulay2/e/cra.cpp
  M2/Macaulay2/e/interface/cra.cpp
  M2/Macaulay2/packages/Complexes.m2
  M2/Macaulay2/packages/Complexes/ChainComplex.m2
  M2/Macaulay2/packages/Complexes/ChainComplexDoc.m2
  M2/Macaulay2/packages/Complexes/ChainComplexMap.m2
  M2/Macaulay2/packages/Complexes/ChainComplexTests.m2
  M2/Macaulay2/packages/MonomialOrbits.m2
Labels: draft

#1722 build and upload tarfile from actions
  .github/workflows/test_build.yml
  M2/Macaulay2/m2/html.m2
  M2/Macaulay2/packages/Text.m2
  M2/cmake/packaging.cmake
Labels: waiting for review

#1716 Quickfix for capture
  M2/Macaulay2/d/actors2.dd
  M2/Macaulay2/d/evaluate.d
  M2/Macaulay2/d/interp.dd
  M2/Macaulay2/d/stdio.d
  M2/Macaulay2/d/stdiop.d
  M2/Macaulay2/e/spair.cpp
  M2/Macaulay2/editors/make-M2-symbols.m2
  M2/Macaulay2/m2/examples.m2
  M2/Macaulay2/m2/installPackage.m2
  M2/Macaulay2/m2/orderedmonoidrings.m2
  M2/Macaulay2/m2/run.m2
  M2/Macaulay2/m2/testing.m2
  M2/Macaulay2/packages/CMakeLists.txt
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc11.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/examples-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/repl.m2
  M2/Macaulay2/packages/MinimalPrimes.m2
  M2/Macaulay2/packages/Polyhedra/documentation/intro.m2
  M2/Macaulay2/packages/Polyhedra/tests/extended/stanleyReisner.m2
  M2/Macaulay2/tests/ComputationsBook/completeIntersections/test.out.expected
  M2/Macaulay2/tests/ComputationsBook/d-modules/test.out.expected
  M2/Macaulay2/tests/ComputationsBook/programming/test.out.expected
  M2/Macaulay2/tests/ComputationsBook/schemes/test.out.expected
  M2/Macaulay2/tests/normal/capture.m2
Labels: waiting for review
