Repository Macaulay2/M2, pull requests merged in 2020-09, with the labels that each got.

#1234 SimpleDoc v1.2
  M2/Macaulay2/d/boost-regex.cpp
  M2/Macaulay2/d/regex.dd
  M2/Macaulay2/editors/CMakeLists.txt
  M2/Macaulay2/editors/make-M2-symbols.m2
  M2/Macaulay2/m2/Makefile.in
  M2/Macaulay2/m2/README.DOC
  M2/Macaulay2/m2/document.m2
  M2/Macaulay2/m2/exports.m2
  M2/Macaulay2/m2/last.m2
  M2/Macaulay2/m2/regex.m2
  M2/Macaulay2/m2/validate.m2
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc14.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc_doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/regex-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/replace-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/select-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/separate-doc.m2
  M2/Macaulay2/packages/Schubert2/doc.m2
  M2/Macaulay2/packages/SimpleDoc.m2
  M2/Macaulay2/packages/SimpleDoc/doc.txt
  M2/Macaulay2/packages/SimpleDoc/example.m2
  M2/Macaulay2/packages/SimpleDoc/helpers-doc.txt
  M2/Macaulay2/packages/SimpleDoc/helpers.m2
  M2/Macaulay2/packages/SimpleDoc/templates.m2
Labels: waiting for review

#1495 This adds the RandomRationalPoints package, and SwitchingFields. It also updates FastLinAlg to use RandomRationalPoints in some cases.
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/FastLinAlg.m2
  M2/Macaulay2/packages/RandomRationalPoints.m2
  M2/Macaulay2/packages/RationalMaps.m2
  M2/Macaulay2/packages/SwitchingFields.m2
Labels: waiting for update

#1461 Replace array<T> with std::vector<T, gc_allocator<T> >
  M2/Macaulay2/e/CMakeLists.txt
  M2/Macaulay2/e/Eschreyer.cpp
  M2/Macaulay2/e/Eschreyer.hpp
  M2/Macaulay2/e/GF.cpp
  M2/Macaulay2/e/array.hpp
  M2/Macaulay2/e/f4/f4-types.hpp
  M2/Macaulay2/e/freemod.cpp
  M2/Macaulay2/e/freemod.hpp
  M2/Macaulay2/e/gb-homog2.cpp
  M2/Macaulay2/e/gb-homog2.hpp
  M2/Macaulay2/e/gb-sugarless.cpp
  M2/Macaulay2/e/gb-sugarless.hpp
  M2/Macaulay2/e/gb-toric.cpp
  M2/Macaulay2/e/gb-toric.hpp
  M2/Macaulay2/e/gb-trace.hpp
  M2/Macaulay2/e/hilb.cpp
  M2/Macaulay2/e/hilb.hpp
  M2/Macaulay2/e/matrix.cpp
  M2/Macaulay2/e/monideal.cpp
  M2/Macaulay2/e/monideal.hpp
  M2/Macaulay2/e/monoid.cpp
  M2/Macaulay2/e/monoid.hpp
  M2/Macaulay2/e/newdelete.hpp
  M2/Macaulay2/e/res-a0-poly.cpp
  M2/Macaulay2/e/res-a0-poly.hpp
  M2/Macaulay2/e/res-a0.cpp
  M2/Macaulay2/e/res-a0.hpp
  M2/Macaulay2/e/res-a1-poly.cpp
  M2/Macaulay2/e/res-a1-poly.hpp
  M2/Macaulay2/e/res-a1.cpp
  M2/Macaulay2/e/res-a1.hpp
  M2/Macaulay2/e/res-a2-gb.cpp
  M2/Macaulay2/e/res-a2.hpp
  M2/Macaulay2/e/style.hpp
Labels: Engine, waiting for review

#1506 CMake maintenance
  M2/BUILD/docker/debian/Dockerfile
  M2/BUILD/docker/ubuntu/Dockerfile
  M2/INSTALL-CMake.md
  M2/Macaulay2/m2/examples.m2
  M2/Macaulay2/m2/packages.m2
  M2/Macaulay2/packages/DecomposableSparseSystems.m2
  M2/cmake/FindCDDLIB.cmake
  M2/cmake/FindFlint.cmake
  M2/cmake/FindGLPK.cmake
  M2/cmake/FindGMP.cmake
  M2/cmake/FindMPIR.cmake
  M2/cmake/FindNTL.cmake
  M2/cmake/build-libraries.cmake
  M2/cmake/check-libraries.cmake
  M2/cmake/configure.cmake
  bugs/dan/0-pari-stacksize
  bugs/dan/1-pari-gmp
  bugs/dan/2-regexpnull.m2
Labels: waiting for review

#1512 Some minor update to SpecialFanoFourfolds and SparseResultants
  M2/Macaulay2/packages/SparseResultants.m2
  M2/Macaulay2/packages/SpecialFanoFourfolds.m2
Labels: waiting for update

#1514 new EagonResolution package
  M2/Macaulay2/packages/=distributed-packages
  M2/Macaulay2/packages/EagonResolution.m2
Labels: waiting for update
