Repository Macaulay2/M2, pull requests merged in 2021-11, with the labels that each got.

#2263 fix documentation of shared symbols
  M2/Macaulay2/m2/document.m2
  M2/Macaulay2/m2/help.m2
Labels: under discussion

#2279 Latest Complexes package, to be placed in Macaulay2 1.19.
  M2/Macaulay2/packages/Complexes.m2
  M2/Macaulay2/packages/Complexes/ChainComplex.m2
  M2/Macaulay2/packages/Complexes/ChainComplexDoc.m2
  M2/Macaulay2/packages/Complexes/ChainComplexMap.m2
  M2/Macaulay2/packages/Complexes/ChainComplexMapDoc.m2
  M2/Macaulay2/packages/Complexes/ChainComplexTests.m2
  M2/Macaulay2/packages/Complexes/Tor.m2
Labels: waiting for update

#2241 division by zero error -- fix #2208
  M2/Macaulay2/e/ZZ.cpp
  M2/Macaulay2/e/ZZp.cpp
  M2/Macaulay2/e/aring-gf-flint.hpp
  M2/Macaulay2/e/aring-zz-flint.hpp
  M2/Macaulay2/e/aring-zzp-ffpack.cpp
  M2/Macaulay2/e/aring-zzp-flint.hpp
  M2/Macaulay2/e/aring-zzp.hpp
  M2/Macaulay2/e/interface/mutable-matrix.cpp
  M2/Macaulay2/m2/quotring.m2
Labels: waiting for review

#2056 Use a nonrecursive algorithms for KBasis
  M2/Macaulay2/e/matrix-kbasis.cpp
  M2/Macaulay2/e/ntuple.hpp
Labels: waiting for review

#2289 Truncations v1.0
  M2/Macaulay2/m2/code.m2
  M2/Macaulay2/m2/expressions.m2
  M2/Macaulay2/m2/help.m2
  M2/Macaulay2/m2/installPackage.m2
  M2/Macaulay2/m2/lists.m2
  M2/Macaulay2/m2/loadsequence
  M2/Macaulay2/m2/matrix1.m2
  M2/Macaulay2/m2/shared.m2
  M2/Macaulay2/m2/varieties.m2
  M2/Macaulay2/packages/Complexes/ChainComplex.m2
  M2/Macaulay2/packages/Complexes/ChainComplexMap.m2
  M2/Macaulay2/packages/FormalGroupLaws.m2
  M2/Macaulay2/packages/IntegralClosure.m2
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/debugging.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc2.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/cohomology-doc.m2
  M2/Macaulay2/packages/NoetherianOperators.m2
  M2/Macaulay2/packages/SpectralSequences.m2
  M2/Macaulay2/packages/Truncations.m2
  M2/Macaulay2/packages/Truncations/docs.m2
  M2/Macaulay2/packages/Truncations/tests.m2
Labels: waiting for review
