Repository Macaulay2/M2, pull requests merged in 2025-03, with the labels that each got.

#3567 Varieties v0.3
  M2/Macaulay2/m2/basis.m2
  M2/Macaulay2/m2/chaincomplexes.m2
  M2/Macaulay2/m2/classes.m2
  M2/Macaulay2/m2/genmat.m2
  M2/Macaulay2/m2/matrix.m2
  M2/Macaulay2/m2/matrix1.m2
  M2/Macaulay2/m2/matrix2.m2
  M2/Macaulay2/m2/methods.m2
  M2/Macaulay2/m2/modules2.m2
  M2/Macaulay2/m2/quotient.m2
  M2/Macaulay2/m2/shared.m2
  M2/Macaulay2/packages/BettiCharacters.m2
  M2/Macaulay2/packages/Complexes/ChainComplex.m2
  M2/Macaulay2/packages/Complexes/ChainComplexMap.m2
  M2/Macaulay2/packages/Isomorphism.m2
  M2/Macaulay2/packages/Macaulay2Doc/changes.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/quotient-remainder-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/functions/random-doc.m2
  M2/Macaulay2/packages/Macaulay2Doc/operators.m2
  M2/Macaulay2/packages/Macaulay2Doc/operators/division.m2
  M2/Macaulay2/packages/Macaulay2Doc/operators/factoring.m2
  M2/Macaulay2/packages/NormalToricVarieties/Divisors.m2
  M2/Macaulay2/packages/NormalToricVarieties/Sheaves.m2
  M2/Macaulay2/packages/NormalToricVarieties/SheavesDocumentation.m2
  M2/Macaulay2/packages/NormalToricVarieties/Tests.m2
  M2/Macaulay2/packages/Schubert2.m2
  M2/Macaulay2/packages/Truncations.m2
  M2/Macaulay2/packages/Truncations/tests.m2
  M2/Macaulay2/packages/Varieties.m2
  M2/Macaulay2/packages/Varieties/SheafComplexes.m2
  M2/Macaulay2/packages/Varieties/SheafMaps.m2
  M2/Macaulay2/packages/Varieties/cotangentSheaf-doc.m2
  M2/Macaulay2/packages/Varieties/doc-complexes.m2
  M2/Macaulay2/packages/Varieties/doc-functors.m2
  M2/Macaulay2/packages/Varieties/doc-maps.m2
  M2/Macaulay2/packages/Varieties/doc-sheaves.m2
  M2/Macaulay2/packages/Varieties/doc-varieties.m2
  M2/Macaulay2/packages/Varieties/examples-ext.m2
  M2/Macaulay2/packages/Varieties/genus-doc.m2
  M2/Macaulay2/packages/Varieties/tangentSheaf-doc.m2
  M2/Macaulay2/packages/Varieties/tests-complexes.m2
  M2/Macaulay2/packages/Varieties/tests-functors.m2
  M2/Macaulay2/packages/Varieties/tests-maps.m2
  M2/Macaulay2/packages/Varieties/tests-sheaves.m2
  M2/Macaulay2/packages/Varieties/tests-varieties.m2
  M2/Macaulay2/tests/normal/augmented-assignment.m2
  M2/Macaulay2/tests/normal/quotient.m2
  M2/Macaulay2/tests/normal/quotientRemainder.m2
Labels: Core

#3705 Define various HAVE_* macros to 1 in cmake build
  M2/include/M2/config.h.cmake
Labels: build issue

#3539 Update RealRoots package to version 1.0 to match JSAG
  M2/Macaulay2/packages/RealRoots.m2
Labels: waiting for review by package author(s)
