Repository Macaulay2/M2, pull requests merged in 2025-05, with the labels that each got.

#3771 Use quotes when linking to oo, ooo, and ooo doc nodes
  M2/Macaulay2/packages/Macaulay2Doc/ov_first_session.m2
Labels: Documentation

#3768 Update Visualize package for leadTerm changes
  M2/Macaulay2/packages/Visualize.m2
Labels: waiting for review

#3792 fixed random for non-free modules
  M2/Macaulay2/m2/genmat.m2
  M2/Macaulay2/tests/normal/randommod.m2
Labels: Core

#3775 Make directProduct a binary method
  M2/Macaulay2/m2/exports.m2
  M2/Macaulay2/m2/shared.m2
  M2/Macaulay2/packages/Graphs.m2
  M2/Macaulay2/packages/Macaulay2Doc/ov_examples.m2
  M2/Macaulay2/packages/Macaulay2Doc/shared.m2
  M2/Macaulay2/packages/Polyhedra/documentation/old_documentation.m2
  M2/Macaulay2/packages/Polyhedra/documentation/working_with_cones.m2
  M2/Macaulay2/packages/Polyhedra/exports.m2
  M2/Macaulay2/packages/Polyhedra/extended/directProduct.m2
  M2/Macaulay2/packages/Polyhedra/tests/legacy_tests_working.m2
Labels: waiting for review by package author(s)

#3716 Improvements to "round"
  M2/Macaulay2/m2/reals.m2
  M2/Macaulay2/packages/Macaulay2Doc/doc_arithmetic.m2
  M2/Macaulay2/tests/normal/numbers.m2
Labels: Core

#3776 Make startup banner webapp-friendly
  M2/Macaulay2/m2/last.m2
Labels: waiting for review, Core
